version: '3'

services:
  db:
    container_name: authDB
    image: postgres:12
    restart: always
    env_file:
      - .env.production
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    container_name: api-auth
#    image: jibber-jabber-user-auth_api #Queda buildeada del docker-compose build, eventualmente pusheada en un repo publico.
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8002:8002
    env_file:
      - .env.production
    depends_on:
      - db

volumes:
  pgdata: