version: '3'

services:
  db:
    container_name: authDB
    image: postgres:12
    restart: always
    env_file:
      - .env.production
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
#
#  api:
#    container_name: api-posts
#    build:
#      context: .
#      dockerfile: Dockerfile.dev
#    ports:
#      - 8000:8080
#    env_file:
#      - .env.production
#    depends_on:
#      - db

volumes:
  pgdata: